name: CMake Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Cache CMake build folder
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ pkg-config \
          libavformat-dev libavcodec-dev libavutil-dev libswscale-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run HelloWorld
      run: ./build/hello_exec

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure